version: '3.9'

services:
  app:
    image: tolgee/tolgee:latest
    volumes:
      - ./data:/data
      - ./config.yml:/config.yml
    ports:
      - '8089:8080'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tolgee-network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: tolgee
      POSTGRES_USER: tolgee_user
      POSTGRES_PASSWORD: tolgee_password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '25432:5432'
    networks:
      - tolgee-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tolgee_user -d tolgee"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/loki
    networks:
      - tolgee-network
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=your-email@gmail.com
      - GF_SMTP_PASSWORD=your-app-specific-password
      - GF_SMTP_FROM_ADDRESS=your-email@gmail.com
      - GF_SMTP_FROM_NAME=Tolgee Monitoring
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - tolgee-network
networks:
  tolgee-network:
    driver: bridge