apiVersion: 1

datasources:
  - name: Loki
    uid: loki          
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      maxLines: 1000
