auth_enabled: false
server:
  http_listen_port: 3100
common:
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
schema_config:
  configs:
  - from: 2025-08-01
    store: tsdb
    object_store: filesystem
    schema: v12
    index:
      prefix: index_
      period: 24h
table_manager:
  retention_period: 168h
compactor:
  retention_enabled: true
  retention_delete_delay: 2h