server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

# Global read limits (valid at top-level, not in a job)
limits_config:
  readline_rate: 100
  readline_burst: 1000

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Set container name label (nice to have)
      - source_labels: ['__meta_docker_container_name']
        target_label: container
        regex: '/(.*)'
      # Route each discovered container to its JSON log file
      - source_labels: ['__meta_docker_container_id']
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/$1-json.log
